# Generated by Django 2.2.5 on 2019-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.CharField(max_length=25)),
                ('github', models.CharField(max_length=255)),
                ('demo', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField()),
                ('description', models.TextField()),
            ],
        ),
    ]
