# Generated by Django 2.2.5 on 2019-09-29 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190928_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
