# Generated by Django 2.2.5 on 2019-09-29 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug_name',
            field=models.SlugField(max_length=300),
        ),
    ]
