# Generated by Django 2.2.5 on 2019-09-29 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190929_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug_name',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
