# Generated by Django 2.2.5 on 2019-09-30 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20190929_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
