# Generated by Django 2.2.5 on 2019-09-30 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_project_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tech',
            new_name='languages',
        ),
    ]
