# Generated by Django 2.2.5 on 2019-09-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.CharField(default='blog', max_length=255),
            preserve_default=False,
        ),
    ]
